name: projtry1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Authentication & Storage
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_auth_web: ^5.8.13
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1
  curved_navigation_bar: ^1.0.3

  # Media & Utils
  image_picker: ^1.1.2
  http: ^1.2.0

  # Core Dependencies
  async: ^2.11.0
  characters: ^1.3.0
  collection: ^1.19.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Testing Dependencies
  boolean_selector: ^2.1.1
  clock: ^1.1.1
  fake_async: ^1.3.1
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  matcher: ^0.12.16+1
  path: ^1.9.0
  source_span: ^1.10.0
  stack_trace: ^1.12.0
  stream_channel: ^2.1.2
  string_scanner: ^1.3.0
  term_glyph: ^1.2.1
  test_api: ^0.7.3
  vm_service: ^14.3.0
  url_launcher: ^6.1.14
flutter:

  uses-material-design: true
  assets:
    - assets/logoflutter.png
    - assets/welcomelogo.png
    - assets/p1.png
    - assets/google_logo.png
    - assets/bgphoto.jpg
    - assets/profile.jpg
    - assets/background.png
    - assets/HI.png
    - assets/skincare.png